### PR TITLE
fix edit sequence diagram

### PR DESCRIPTION
**Pull request by seadragon2000341**
- cr returned
- updateselectedinternship

### CODE REVIEW

**Comment by potty10** [comment]
Thanks for the edit. Should there be a method call here?

image

**Comment by seadragon2000341** [comment]
> Thanks for the edit. Should there be a method call here?
> 
> image

Im not too sure about this actually. Because the method call is createEditedInternship(internshipToEdit, EditInternshipDescriptor) so it dosent actually go into EditInternshipDescriptor via the method call

**Comment by eugenetangkj** [comment]
@seadragon2000341 

The `createEditedInternship(internshipToEdit, EditInternshipDescriptor)` is a static method of the class `EditCommand`, so I believe it should be making a call to the **class** `EditCommand` instead of an object of `EditInternshipDescriptor`.

Referring to the tutorial notes, it should look something like this:
image


Does it make more sense if we amend it as such?

**Comment by seadragon2000341** [comment]
@eugenetangkj @potty10 

Ive changed to this image!
- edit command calls its own method (create edited internship)
- edit internshipdescriptor gets destroyed when edit command is destroyed (since editinternshipdescriptor is aprt of edit command)
image

**Comment by eugenetangkj** [comment]
Thanks for the effort! Looks great to merge 👍

**Pull request merged**
