### PR TITLE
Fix integer overflow bug

### PR DESCRIPTION
**Pull request by kohkaixun**

### CODE REVIEW

**Comment by seadragon2000341** [comment]
@kohkaixun there's merge conflict, can try and resolve?

**Comment by eugenetangkj** [comment]
I have posted a query on the [forum](https://github.com/nus-cs2103-AY2223S2/forum/issues/319) to check if such a fix is allowed. Let's wait for Prof's reply before proceeding?

**Comment by kohkaixun** [comment]
Oh no, ok we can implement it in the dg instead @eugenetangkj .

**Comment by eugenetangkj** [comment]
Cannot fix, but explained in developer guide at #202.

**Pull request closed without merging**
